### ISSUE TITLE
ValidationError: Parameters: [LoadBalancerWafWebACLIdParameter] do not exist in the template

### ISSUE THREAD

**Issue by ruudk** [zalando-incubator/kube-ingress-aws-controller#331]
After upgrading the controller from `v0.9.6` to latest I'm getting:
```
private-ingress-controller-5b444bb4d4-4hvbn controller 2020/04/01 17:49:54 DEBUG: Validate Response cloudformation/UpdateStack failed, attempt 0/3, error ValidationError: Parameters: [LoadBalancerWafWebACLIdParameter] do not exist in the template
private-ingress-controller-5b444bb4d4-4hvbn controller 	status code: 400, request id: 70b42810-964d-44d3-bdec-15ec6834026f
private-ingress-controller-5b444bb4d4-4hvbn controller time="2020-04-01T17:49:54Z" level=error msg="updateStack(map[\"arn:aws:acm:eu-west-1:355892651979:certificate/b9a91d7b-74a3-4534-a9c1-3fa718c7bb87\":\"0001-01-01 00:00:00 +0000 UTC\" \"arn:aws:acm:eu-west-1:355892651979:certificate/c20bb770-16ec-408f-8d1f-be3170277d0a\":\"0001-01-01 00:00:00 +0000 UTC\"]) failed: ValidationError: Parameters: [LoadBalancerWafWebACLIdParameter] do not exist in the template\n\tstatus code: 400, request id: 70b42810-964d-44d3-bdec-15ec6834026f"
```

@aryszka Did you encounter the same issue in https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/326?

**Comment by mikkeloscar** [comment]
@ruudk yes, we're working on a fix today!

**Comment by ruudk** [comment]
@mikkeloscar Any news on this? :)

**Comment by mikkeloscar** [comment]
Should be fixed by #342 from what i understand.

**Comment by ruudk** [comment]
This problem still exists with the latest release v0.10.12
```
private-ingress-controller-768684f8fb-wr2kg controller 2020/04/21 08:16:44 DEBUG: Validate Response cloudformation/UpdateStack failed, attempt 0/3, error ValidationError: Parameters: [LoadBalancerWAFWebACLIDParameter] must have values
private-ingress-controller-768684f8fb-wr2kg controller 	status code: 400, request id: 699eaf95-2cdb-41e0-b9e7-fe49ba0e18c0
private-ingress-controller-768684f8fb-wr2kg controller time="2020-04-21T08:16:44Z" level=error msg="updateStack(map[\"arn:aws:acm:eu-west-1:xxxx:certificate/xxx\":\"0001-01-01 00:00:00 +0000 UTC\"]) failed: ValidationError: Parameters: [LoadBalancerWAFWebACLIDParameter] must have values\n\tstatus code: 400, request id: 699eaf95-2cdb-41e0-b9e7-fe49ba0e18c0"
```

Any idea @mikkeloscar @aryszka ?

**Comment by szuecs** [comment]
@ruudk ad far as I understand you don’t use a waf, right?

I think #342 just added the branch to choose between v1 and v2.
The default parameter is empty string and we might not validate that we have an empty string to change the cf stack to not have a waf at all. I just read the pr, so I can be wrong, but it feels like it is the case

**Comment by ruudk** [comment]
Indeed, we don't use WAF.

**Comment by mikkeloscar** [comment]
@ruudk Sorry about that, should be finally fixed now!

**Comment by ruudk** [comment]
Works, thanks for the fast fix!
